#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Wataru Suenaga
# SPDX-License-Identifier: GPL-3.0-only

from collections import Counter
import sys

def main():
    text = sys.stdin.read().strip()

    if not text:
        print("No input", file=sys.stderr)
        exit(1)

    c = Counter(text)
    
    for char, count in c.items():
        print(f"{char}: {count}")

if __name__ == "__main__":
    main()
# This software package is licensed under the GPL-3.0 License, and redistribution and usage are permitted under its terms.
# © 2024:Wataru Suenaga
