#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Wataru Suenaga
# SPDX-License-Identifier: GPL-3.0-only

from collections import Counter
import sys

if len(sys.argv) < 2:
    print("Usage: ./count 'text'")
    exit()

text = sys.argv[1]

if not text.strip():
    print("No input")
    exit()

c = Counter(text)

print(c)

# This software package is licensed under the GPL-3.0 License, and redistribution and usage are permitted under its terms.
# © 2024:Wataru Suenaga
